enum UnicodeBlock {
  unicodeBasicLatin,
  unicodeLatin1Supplement,
  unicodeLatinExtendedA,
  unicodeLatinExtendedB,
  unicodeIpaExtensions,
  unicodeSpacingModifierLetters,
  unicodeCombiningDiacriticalMarks,
  unicodeGreekAndCoptic,
  unicodeCyrillic,
  unicodeCyrillicSupplement,
  unicodeArmenian,
  unicodeHebrew,
  unicodeArabic,
  unicodeSyriac,
  unicodeArabicSupplement,
  unicodeThaana,
  unicodeNko,
  unicodeSamaritan,
  unicodeMandaic,
  unicodeArabicExtendedA,
  unicodeDevanagari,
  unicodeBengali,
  unicodeGurmukhi,
  unicodeGujarati,
  unicodeOriya,
  unicodeTamil,
  unicodeTelugu,
  unicodeKannada,
  unicodeMalayalam,
  unicodeSinhala,
  unicodeThai,
  unicodeLao,
  unicodeTibetan,
  unicodeMyanmar,
  unicodeGeorgian,
  unicodeHangulJamo,
  unicodeEthiopic,
  unicodeEthiopicSupplement,
  unicodeCherokee,
  unicodeUnifiedCanadianAboriginalSyllabics,
  unicodeOgham,
  unicodeRunic,
  unicodeTagalog,
  unicodeHanunoo,
  unicodeBuhid,
  unicodeTagbanwa,
  unicodeKhmer,
  unicodeMongolian,
  unicodeUnifiedCanadianAboriginalSyllabicsExtended,
  unicodeLimbu,
  unicodeTaiLe,
  unicodeNewTaiLue,
  unicodeKhmerSymbols,
  unicodeBuginese,
  unicodeTaiTham,
  unicodeBalinese,
  unicodeSundanese,
  unicodeBatak,
  unicodeLepcha,
  unicodeOlChiki,
  unicodeSundaneseSupplement,
  unicodeVedicExtensions,
  unicodePhoneticExtensions,
  unicodePhoneticExtensionsSupplement,
  unicodeCombiningDiacriticalMarksSupplement,
  unicodeLatinExtendedAdditional,
  unicodeGreekExtended,
  unicodeGeneralPunctuation,
  unicodeSuperscriptsAndSubscripts,
  unicodeCurrencySymbols,
  unicodeCombiningDiacriticalMarksForSymbols,
  unicodeLetterlikeSymbols,
  unicodeNumberForms,
  unicodeArrows,
  unicodeMathematicalOperators,
  unicodeMiscellaneousTechnical,
  unicodeControlPictures,
  unicodeOpticalCharacterRecognition,
  unicodeEnclosedAlphanumerics,
  unicodeBoxDrawing,
  unicodeBlockElements,
  unicodeGeometricShapes,
  unicodeMiscellaneousSymbols,
  unicodeDingbats,
  unicodeMiscellaneousMathematicalSymbolsA,
  unicodeSupplementalArrowsA,
  unicodeBraillePatterns,
  unicodeSupplementalArrowsB,
  unicodeMiscellaneousMathematicalSymbolsB,
  unicodeSupplementalMathematicalOperators,
  unicodeMiscellaneousSymbolsAndArrows,
  unicodeGlagolitic,
  unicodeLatinExtendedC,
  unicodeCoptic,
  unicodeGeorgianSupplement,
  unicodeTifinagh,
  unicodeEthiopicExtended,
  unicodeCyrillicExtendedA,
  unicodeSupplementalPunctuation,
  unicodeCjkRadicalsSupplement,
  unicodeKangxiRadicals,
  unicodeIdeographicDescriptionCharacters,
  unicodeCjkSymbolsAndPunctuation,
  unicodeHiragana,
  unicodeKatakana,
  unicodeBopomofo,
  unicodeHangulCompatibilityJamo,
  unicodeKanbun,
  unicodeBopomofoExtended,
  unicodeCjkStrokes,
  unicodeKatakanaPhoneticExtensions,
  unicodeEnclosedCjkLettersAndMonths,
  unicodeCjkCompatibility,
  unicodeCjkUnifiedIdeographsExtensionA,
  unicodeYijingHexagramSymbols,
  unicodeCjkUnifiedIdeographs,
  unicodeYiSyllables,
  unicodeYiRadicals,
  unicodeLisu,
  unicodeVai,
  unicodeCyrillicExtendedB,
  unicodeBamum,
  unicodeModifierToneLetters,
  unicodeLatinExtendedD,
  unicodeSylotiNagri,
  unicodeCommonIndicNumberForms,
  unicodePhagsPa,
  unicodeSaurashtra,
  unicodeDevanagariExtended,
  unicodeKayahLi,
  unicodeRejang,
  unicodeHangulJamoExtendedA,
  unicodeJavanese,
  unicodeCham,
  unicodeMyanmarExtendedA,
  unicodeTaiViet,
  unicodeMeeteiMayekExtensions,
  unicodeEthiopicExtendedA,
  unicodeMeeteiMayek,
  unicodeHangulSyllables,
  unicodeHangulJamoExtendedB,
  unicodeHighSurrogates,
  unicodeHighPrivateUseSurrogates,
  unicodeLowSurrogates,
  unicodePrivateUseArea,
  unicodeCjkCompatibilityIdeographs,
  unicodeAlphabeticPresentationForms,
  unicodeArabicPresentationFormsA,
  unicodeVariationSelectors,
  unicodeVerticalForms,
  unicodeCombiningHalfMarks,
  unicodeCjkCompatibilityForms,
  unicodeSmallFormVariants,
  unicodeArabicPresentationFormsB,
  unicodeHalfwidthAndFullwidthForms,
  unicodeSpecials,
  unicodeLinearBSyllabary,
  unicodeLinearBIdeograms,
  unicodeAegeanNumbers,
  unicodeAncientGreekNumbers,
  unicodeAncientSymbols,
  unicodePhaistosDisc,
  unicodeLycian,
  unicodeCarian,
  unicodeOldItalic,
  unicodeGothic,
  unicodeUgaritic,
  unicodeOldPersian,
  unicodeDeseret,
  unicodeShavian,
  unicodeOsmanya,
  unicodeCypriotSyllabary,
  unicodeImperialAramaic,
  unicodePhoenician,
  unicodeLydian,
  unicodeMeroiticHieroglyphs,
  unicodeMeroiticCursive,
  unicodeKharoshthi,
  unicodeOldSouthArabian,
  unicodeAvestan,
  unicodeInscriptionalParthian,
  unicodeInscriptionalPahlavi,
  unicodeOldTurkic,
  unicodeRumiNumeralSymbols,
  unicodeBrahmi,
  unicodeKaithi,
  unicodeSoraSompeng,
  unicodeChakma,
  unicodeSharada,
  unicodeTakri,
  unicodeCuneiform,
  unicodeCuneiformNumbersAndPunctuation,
  unicodeEgyptianHieroglyphs,
  unicodeBamumSupplement,
  unicodeMiao,
  unicodeKanaSupplement,
  unicodeByzantineMusicalSymbols,
  unicodeMusicalSymbols,
  unicodeAncientGreekMusicalNotation,
  unicodeTaiXuanJingSymbols,
  unicodeCountingRodNumerals,
  unicodeMathematicalAlphanumericSymbols,
  unicodeArabicMathematicalAlphabeticSymbols,
  unicodeMahjongTiles,
  unicodeDominoTiles,
  unicodePlayingCards,
  unicodeEnclosedAlphanumericSupplement,
  unicodeEnclosedIdeographicSupplement,
  unicodeMiscellaneousSymbolsAndPictographs,
  unicodeEmoticons,
  unicodeTransportAndMapSymbols,
  unicodeAlchemicalSymbols,
  unicodeCjkUnifiedIdeographsExtensionB,
  unicodeCjkUnifiedIdeographsExtensionC,
  unicodeCjkUnifiedIdeographsExtensionD,
  unicodeCjkCompatibilityIdeographsSupplement,
  unicodeTags,
  unicodeVariationSelectorsSupplement,
  unicodeSupplementaryPrivateUseAreaA,
  unicodeSupplementaryPrivateUseAreaB
}

class Tuple3<T1, T2, T3> {
  final T1 item1;
  final T2 item2;
  final T3 item3;

  const Tuple3(this.item1, this.item2, this.item3);
}

const _unicodeBlocks = [
  Tuple3(UnicodeBlock.unicodeBasicLatin, 0x0000, 0x007F),
  Tuple3(UnicodeBlock.unicodeLatin1Supplement, 0x0080, 0x00FF),
  Tuple3(UnicodeBlock.unicodeLatinExtendedA, 0x0100, 0x017F),
  Tuple3(UnicodeBlock.unicodeLatinExtendedB, 0x0180, 0x024F),
  Tuple3(UnicodeBlock.unicodeIpaExtensions, 0x0250, 0x02AF),
  Tuple3(UnicodeBlock.unicodeSpacingModifierLetters, 0x02B0, 0x02FF),
  Tuple3(UnicodeBlock.unicodeCombiningDiacriticalMarks, 0x0300, 0x036F),
  Tuple3(UnicodeBlock.unicodeGreekAndCoptic, 0x0370, 0x03FF),
  Tuple3(UnicodeBlock.unicodeCyrillic, 0x0400, 0x04FF),
  Tuple3(UnicodeBlock.unicodeCyrillicSupplement, 0x0500, 0x052F),
  Tuple3(UnicodeBlock.unicodeArmenian, 0x0530, 0x058F),
  Tuple3(UnicodeBlock.unicodeHebrew, 0x0590, 0x05FF),
  Tuple3(UnicodeBlock.unicodeArabic, 0x0600, 0x06FF),
  Tuple3(UnicodeBlock.unicodeSyriac, 0x0700, 0x074F),
  Tuple3(UnicodeBlock.unicodeArabicSupplement, 0x0750, 0x077F),
  Tuple3(UnicodeBlock.unicodeThaana, 0x0780, 0x07BF),
  Tuple3(UnicodeBlock.unicodeNko, 0x07C0, 0x07FF),
  Tuple3(UnicodeBlock.unicodeSamaritan, 0x0800, 0x083F),
  Tuple3(UnicodeBlock.unicodeMandaic, 0x0840, 0x085F),
  Tuple3(UnicodeBlock.unicodeArabicExtendedA, 0x08A0, 0x08FF),
  Tuple3(UnicodeBlock.unicodeDevanagari, 0x0900, 0x097F),
  Tuple3(UnicodeBlock.unicodeBengali, 0x0980, 0x09FF),
  Tuple3(UnicodeBlock.unicodeGurmukhi, 0x0A00, 0x0A7F),
  Tuple3(UnicodeBlock.unicodeGujarati, 0x0A80, 0x0AFF),
  Tuple3(UnicodeBlock.unicodeOriya, 0x0B00, 0x0B7F),
  Tuple3(UnicodeBlock.unicodeTamil, 0x0B80, 0x0BFF),
  Tuple3(UnicodeBlock.unicodeTelugu, 0x0C00, 0x0C7F),
  Tuple3(UnicodeBlock.unicodeKannada, 0x0C80, 0x0CFF),
  Tuple3(UnicodeBlock.unicodeMalayalam, 0x0D00, 0x0D7F),
  Tuple3(UnicodeBlock.unicodeSinhala, 0x0D80, 0x0DFF),
  Tuple3(UnicodeBlock.unicodeThai, 0x0E00, 0x0E7F),
  Tuple3(UnicodeBlock.unicodeLao, 0x0E80, 0x0EFF),
  Tuple3(UnicodeBlock.unicodeTibetan, 0x0F00, 0x0FFF),
  Tuple3(UnicodeBlock.unicodeMyanmar, 0x1000, 0x109F),
  Tuple3(UnicodeBlock.unicodeGeorgian, 0x10A0, 0x10FF),
  Tuple3(UnicodeBlock.unicodeHangulJamo, 0x1100, 0x11FF),
  Tuple3(UnicodeBlock.unicodeEthiopic, 0x1200, 0x137F),
  Tuple3(UnicodeBlock.unicodeEthiopicSupplement, 0x1380, 0x139F),
  Tuple3(UnicodeBlock.unicodeCherokee, 0x13A0, 0x13FF),
  Tuple3(
      UnicodeBlock.unicodeUnifiedCanadianAboriginalSyllabics, 0x1400, 0x167F),
  Tuple3(UnicodeBlock.unicodeOgham, 0x1680, 0x169F),
  Tuple3(UnicodeBlock.unicodeRunic, 0x16A0, 0x16FF),
  Tuple3(UnicodeBlock.unicodeTagalog, 0x1700, 0x171F),
  Tuple3(UnicodeBlock.unicodeHanunoo, 0x1720, 0x173F),
  Tuple3(UnicodeBlock.unicodeBuhid, 0x1740, 0x175F),
  Tuple3(UnicodeBlock.unicodeTagbanwa, 0x1760, 0x177F),
  Tuple3(UnicodeBlock.unicodeKhmer, 0x1780, 0x17FF),
  Tuple3(UnicodeBlock.unicodeMongolian, 0x1800, 0x18AF),
  Tuple3(UnicodeBlock.unicodeUnifiedCanadianAboriginalSyllabicsExtended, 0x18B0,
      0x18FF),
  Tuple3(UnicodeBlock.unicodeLimbu, 0x1900, 0x194F),
  Tuple3(UnicodeBlock.unicodeTaiLe, 0x1950, 0x197F),
  Tuple3(UnicodeBlock.unicodeNewTaiLue, 0x1980, 0x19DF),
  Tuple3(UnicodeBlock.unicodeKhmerSymbols, 0x19E0, 0x19FF),
  Tuple3(UnicodeBlock.unicodeBuginese, 0x1A00, 0x1A1F),
  Tuple3(UnicodeBlock.unicodeTaiTham, 0x1A20, 0x1AAF),
  Tuple3(UnicodeBlock.unicodeBalinese, 0x1B00, 0x1B7F),
  Tuple3(UnicodeBlock.unicodeSundanese, 0x1B80, 0x1BBF),
  Tuple3(UnicodeBlock.unicodeBatak, 0x1BC0, 0x1BFF),
  Tuple3(UnicodeBlock.unicodeLepcha, 0x1C00, 0x1C4F),
  Tuple3(UnicodeBlock.unicodeOlChiki, 0x1C50, 0x1C7F),
  Tuple3(UnicodeBlock.unicodeSundaneseSupplement, 0x1CC0, 0x1CCF),
  Tuple3(UnicodeBlock.unicodeVedicExtensions, 0x1CD0, 0x1CFF),
  Tuple3(UnicodeBlock.unicodePhoneticExtensions, 0x1D00, 0x1D7F),
  Tuple3(UnicodeBlock.unicodePhoneticExtensionsSupplement, 0x1D80, 0x1DBF),
  Tuple3(
      UnicodeBlock.unicodeCombiningDiacriticalMarksSupplement, 0x1DC0, 0x1DFF),
  Tuple3(UnicodeBlock.unicodeLatinExtendedAdditional, 0x1E00, 0x1EFF),
  Tuple3(UnicodeBlock.unicodeGreekExtended, 0x1F00, 0x1FFF),
  Tuple3(UnicodeBlock.unicodeGeneralPunctuation, 0x2000, 0x206F),
  Tuple3(UnicodeBlock.unicodeSuperscriptsAndSubscripts, 0x2070, 0x209F),
  Tuple3(UnicodeBlock.unicodeCurrencySymbols, 0x20A0, 0x20CF),
  Tuple3(
      UnicodeBlock.unicodeCombiningDiacriticalMarksForSymbols, 0x20D0, 0x20FF),
  Tuple3(UnicodeBlock.unicodeLetterlikeSymbols, 0x2100, 0x214F),
  Tuple3(UnicodeBlock.unicodeNumberForms, 0x2150, 0x218F),
  Tuple3(UnicodeBlock.unicodeArrows, 0x2190, 0x21FF),
  Tuple3(UnicodeBlock.unicodeMathematicalOperators, 0x2200, 0x22FF),
  Tuple3(UnicodeBlock.unicodeMiscellaneousTechnical, 0x2300, 0x23FF),
  Tuple3(UnicodeBlock.unicodeControlPictures, 0x2400, 0x243F),
  Tuple3(UnicodeBlock.unicodeOpticalCharacterRecognition, 0x2440, 0x245F),
  Tuple3(UnicodeBlock.unicodeEnclosedAlphanumerics, 0x2460, 0x24FF),
  Tuple3(UnicodeBlock.unicodeBoxDrawing, 0x2500, 0x257F),
  Tuple3(UnicodeBlock.unicodeBlockElements, 0x2580, 0x259F),
  Tuple3(UnicodeBlock.unicodeGeometricShapes, 0x25A0, 0x25FF),
  Tuple3(UnicodeBlock.unicodeMiscellaneousSymbols, 0x2600, 0x26FF),
  Tuple3(UnicodeBlock.unicodeDingbats, 0x2700, 0x27BF),
  Tuple3(UnicodeBlock.unicodeMiscellaneousMathematicalSymbolsA, 0x27C0, 0x27EF),
  Tuple3(UnicodeBlock.unicodeSupplementalArrowsA, 0x27F0, 0x27FF),
  Tuple3(UnicodeBlock.unicodeBraillePatterns, 0x2800, 0x28FF),
  Tuple3(UnicodeBlock.unicodeSupplementalArrowsB, 0x2900, 0x297F),
  Tuple3(UnicodeBlock.unicodeMiscellaneousMathematicalSymbolsB, 0x2980, 0x29FF),
  Tuple3(UnicodeBlock.unicodeSupplementalMathematicalOperators, 0x2A00, 0x2AFF),
  Tuple3(UnicodeBlock.unicodeMiscellaneousSymbolsAndArrows, 0x2B00, 0x2BFF),
  Tuple3(UnicodeBlock.unicodeGlagolitic, 0x2C00, 0x2C5F),
  Tuple3(UnicodeBlock.unicodeLatinExtendedC, 0x2C60, 0x2C7F),
  Tuple3(UnicodeBlock.unicodeCoptic, 0x2C80, 0x2CFF),
  Tuple3(UnicodeBlock.unicodeGeorgianSupplement, 0x2D00, 0x2D2F),
  Tuple3(UnicodeBlock.unicodeTifinagh, 0x2D30, 0x2D7F),
  Tuple3(UnicodeBlock.unicodeEthiopicExtended, 0x2D80, 0x2DDF),
  Tuple3(UnicodeBlock.unicodeCyrillicExtendedA, 0x2DE0, 0x2DFF),
  Tuple3(UnicodeBlock.unicodeSupplementalPunctuation, 0x2E00, 0x2E7F),
  Tuple3(UnicodeBlock.unicodeCjkRadicalsSupplement, 0x2E80, 0x2EFF),
  Tuple3(UnicodeBlock.unicodeKangxiRadicals, 0x2F00, 0x2FDF),
  Tuple3(UnicodeBlock.unicodeIdeographicDescriptionCharacters, 0x2FF0, 0x2FFF),
  Tuple3(UnicodeBlock.unicodeCjkSymbolsAndPunctuation, 0x3000, 0x303F),
  Tuple3(UnicodeBlock.unicodeHiragana, 0x3040, 0x309F),
  Tuple3(UnicodeBlock.unicodeKatakana, 0x30A0, 0x30FF),
  Tuple3(UnicodeBlock.unicodeBopomofo, 0x3100, 0x312F),
  Tuple3(UnicodeBlock.unicodeHangulCompatibilityJamo, 0x3130, 0x318F),
  Tuple3(UnicodeBlock.unicodeKanbun, 0x3190, 0x319F),
  Tuple3(UnicodeBlock.unicodeBopomofoExtended, 0x31A0, 0x31BF),
  Tuple3(UnicodeBlock.unicodeCjkStrokes, 0x31C0, 0x31EF),
  Tuple3(UnicodeBlock.unicodeKatakanaPhoneticExtensions, 0x31F0, 0x31FF),
  Tuple3(UnicodeBlock.unicodeEnclosedCjkLettersAndMonths, 0x3200, 0x32FF),
  Tuple3(UnicodeBlock.unicodeCjkCompatibility, 0x3300, 0x33FF),
  Tuple3(UnicodeBlock.unicodeCjkUnifiedIdeographsExtensionA, 0x3400, 0x4DBF),
  Tuple3(UnicodeBlock.unicodeYijingHexagramSymbols, 0x4DC0, 0x4DFF),
  Tuple3(UnicodeBlock.unicodeCjkUnifiedIdeographs, 0x4E00, 0x9FFF),
  Tuple3(UnicodeBlock.unicodeYiSyllables, 0xA000, 0xA48F),
  Tuple3(UnicodeBlock.unicodeYiRadicals, 0xA490, 0xA4CF),
  Tuple3(UnicodeBlock.unicodeLisu, 0xA4D0, 0xA4FF),
  Tuple3(UnicodeBlock.unicodeVai, 0xA500, 0xA63F),
  Tuple3(UnicodeBlock.unicodeCyrillicExtendedB, 0xA640, 0xA69F),
  Tuple3(UnicodeBlock.unicodeBamum, 0xA6A0, 0xA6FF),
  Tuple3(UnicodeBlock.unicodeModifierToneLetters, 0xA700, 0xA71F),
  Tuple3(UnicodeBlock.unicodeLatinExtendedD, 0xA720, 0xA7FF),
  Tuple3(UnicodeBlock.unicodeSylotiNagri, 0xA800, 0xA82F),
  Tuple3(UnicodeBlock.unicodeCommonIndicNumberForms, 0xA830, 0xA83F),
  Tuple3(UnicodeBlock.unicodePhagsPa, 0xA840, 0xA87F),
  Tuple3(UnicodeBlock.unicodeSaurashtra, 0xA880, 0xA8DF),
  Tuple3(UnicodeBlock.unicodeDevanagariExtended, 0xA8E0, 0xA8FF),
  Tuple3(UnicodeBlock.unicodeKayahLi, 0xA900, 0xA92F),
  Tuple3(UnicodeBlock.unicodeRejang, 0xA930, 0xA95F),
  Tuple3(UnicodeBlock.unicodeHangulJamoExtendedA, 0xA960, 0xA97F),
  Tuple3(UnicodeBlock.unicodeJavanese, 0xA980, 0xA9DF),
  Tuple3(UnicodeBlock.unicodeCham, 0xAA00, 0xAA5F),
  Tuple3(UnicodeBlock.unicodeMyanmarExtendedA, 0xAA60, 0xAA7F),
  Tuple3(UnicodeBlock.unicodeTaiViet, 0xAA80, 0xAADF),
  Tuple3(UnicodeBlock.unicodeMeeteiMayekExtensions, 0xAAE0, 0xAAFF),
  Tuple3(UnicodeBlock.unicodeEthiopicExtendedA, 0xAB00, 0xAB2F),
  Tuple3(UnicodeBlock.unicodeMeeteiMayek, 0xABC0, 0xABFF),
  Tuple3(UnicodeBlock.unicodeHangulSyllables, 0xAC00, 0xD7AF),
  Tuple3(UnicodeBlock.unicodeHangulJamoExtendedB, 0xD7B0, 0xD7FF),
  Tuple3(UnicodeBlock.unicodeHighSurrogates, 0xD800, 0xDB7F),
  Tuple3(UnicodeBlock.unicodeHighPrivateUseSurrogates, 0xDB80, 0xDBFF),
  Tuple3(UnicodeBlock.unicodeLowSurrogates, 0xDC00, 0xDFFF),
  Tuple3(UnicodeBlock.unicodePrivateUseArea, 0xE000, 0xF8FF),
  Tuple3(UnicodeBlock.unicodeCjkCompatibilityIdeographs, 0xF900, 0xFAFF),
  Tuple3(UnicodeBlock.unicodeAlphabeticPresentationForms, 0xFB00, 0xFB4F),
  Tuple3(UnicodeBlock.unicodeArabicPresentationFormsA, 0xFB50, 0xFDFF),
  Tuple3(UnicodeBlock.unicodeVariationSelectors, 0xFE00, 0xFE0F),
  Tuple3(UnicodeBlock.unicodeVerticalForms, 0xFE10, 0xFE1F),
  Tuple3(UnicodeBlock.unicodeCombiningHalfMarks, 0xFE20, 0xFE2F),
  Tuple3(UnicodeBlock.unicodeCjkCompatibilityForms, 0xFE30, 0xFE4F),
  Tuple3(UnicodeBlock.unicodeSmallFormVariants, 0xFE50, 0xFE6F),
  Tuple3(UnicodeBlock.unicodeArabicPresentationFormsB, 0xFE70, 0xFEFF),
  Tuple3(UnicodeBlock.unicodeHalfwidthAndFullwidthForms, 0xFF00, 0xFFEF),
  Tuple3(UnicodeBlock.unicodeSpecials, 0xFFF0, 0xFFFF),
  Tuple3(UnicodeBlock.unicodeLinearBSyllabary, 0x10000, 0x1007F),
  Tuple3(UnicodeBlock.unicodeLinearBIdeograms, 0x10080, 0x100FF),
  Tuple3(UnicodeBlock.unicodeAegeanNumbers, 0x10100, 0x1013F),
  Tuple3(UnicodeBlock.unicodeAncientGreekNumbers, 0x10140, 0x1018F),
  Tuple3(UnicodeBlock.unicodeAncientSymbols, 0x10190, 0x101CF),
  Tuple3(UnicodeBlock.unicodePhaistosDisc, 0x101D0, 0x101FF),
  Tuple3(UnicodeBlock.unicodeLycian, 0x10280, 0x1029F),
  Tuple3(UnicodeBlock.unicodeCarian, 0x102A0, 0x102DF),
  Tuple3(UnicodeBlock.unicodeOldItalic, 0x10300, 0x1032F),
  Tuple3(UnicodeBlock.unicodeGothic, 0x10330, 0x1034F),
  Tuple3(UnicodeBlock.unicodeUgaritic, 0x10380, 0x1039F),
  Tuple3(UnicodeBlock.unicodeOldPersian, 0x103A0, 0x103DF),
  Tuple3(UnicodeBlock.unicodeDeseret, 0x10400, 0x1044F),
  Tuple3(UnicodeBlock.unicodeShavian, 0x10450, 0x1047F),
  Tuple3(UnicodeBlock.unicodeOsmanya, 0x10480, 0x104AF),
  Tuple3(UnicodeBlock.unicodeCypriotSyllabary, 0x10800, 0x1083F),
  Tuple3(UnicodeBlock.unicodeImperialAramaic, 0x10840, 0x1085F),
  Tuple3(UnicodeBlock.unicodePhoenician, 0x10900, 0x1091F),
  Tuple3(UnicodeBlock.unicodeLydian, 0x10920, 0x1093F),
  Tuple3(UnicodeBlock.unicodeMeroiticHieroglyphs, 0x10980, 0x1099F),
  Tuple3(UnicodeBlock.unicodeMeroiticCursive, 0x109A0, 0x109FF),
  Tuple3(UnicodeBlock.unicodeKharoshthi, 0x10A00, 0x10A5F),
  Tuple3(UnicodeBlock.unicodeOldSouthArabian, 0x10A60, 0x10A7F),
  Tuple3(UnicodeBlock.unicodeAvestan, 0x10B00, 0x10B3F),
  Tuple3(UnicodeBlock.unicodeInscriptionalParthian, 0x10B40, 0x10B5F),
  Tuple3(UnicodeBlock.unicodeInscriptionalPahlavi, 0x10B60, 0x10B7F),
  Tuple3(UnicodeBlock.unicodeOldTurkic, 0x10C00, 0x10C4F),
  Tuple3(UnicodeBlock.unicodeRumiNumeralSymbols, 0x10E60, 0x10E7F),
  Tuple3(UnicodeBlock.unicodeBrahmi, 0x11000, 0x1107F),
  Tuple3(UnicodeBlock.unicodeKaithi, 0x11080, 0x110CF),
  Tuple3(UnicodeBlock.unicodeSoraSompeng, 0x110D0, 0x110FF),
  Tuple3(UnicodeBlock.unicodeChakma, 0x11100, 0x1114F),
  Tuple3(UnicodeBlock.unicodeSharada, 0x11180, 0x111DF),
  Tuple3(UnicodeBlock.unicodeTakri, 0x11680, 0x116CF),
  Tuple3(UnicodeBlock.unicodeCuneiform, 0x12000, 0x123FF),
  Tuple3(UnicodeBlock.unicodeCuneiformNumbersAndPunctuation, 0x12400, 0x1247F),
  Tuple3(UnicodeBlock.unicodeEgyptianHieroglyphs, 0x13000, 0x1342F),
  Tuple3(UnicodeBlock.unicodeBamumSupplement, 0x16800, 0x16A3F),
  Tuple3(UnicodeBlock.unicodeMiao, 0x16F00, 0x16F9F),
  Tuple3(UnicodeBlock.unicodeKanaSupplement, 0x1B000, 0x1B0FF),
  Tuple3(UnicodeBlock.unicodeByzantineMusicalSymbols, 0x1D000, 0x1D0FF),
  Tuple3(UnicodeBlock.unicodeMusicalSymbols, 0x1D100, 0x1D1FF),
  Tuple3(UnicodeBlock.unicodeAncientGreekMusicalNotation, 0x1D200, 0x1D24F),
  Tuple3(UnicodeBlock.unicodeTaiXuanJingSymbols, 0x1D300, 0x1D35F),
  Tuple3(UnicodeBlock.unicodeCountingRodNumerals, 0x1D360, 0x1D37F),
  Tuple3(UnicodeBlock.unicodeMathematicalAlphanumericSymbols, 0x1D400, 0x1D7FF),
  Tuple3(UnicodeBlock.unicodeArabicMathematicalAlphabeticSymbols, 0x1EE00,
      0x1EEFF),
  Tuple3(UnicodeBlock.unicodeMahjongTiles, 0x1F000, 0x1F02F),
  Tuple3(UnicodeBlock.unicodeDominoTiles, 0x1F030, 0x1F09F),
  Tuple3(UnicodeBlock.unicodePlayingCards, 0x1F0A0, 0x1F0FF),
  Tuple3(UnicodeBlock.unicodeEnclosedAlphanumericSupplement, 0x1F100, 0x1F1FF),
  Tuple3(UnicodeBlock.unicodeEnclosedIdeographicSupplement, 0x1F200, 0x1F2FF),
  Tuple3(
      UnicodeBlock.unicodeMiscellaneousSymbolsAndPictographs, 0x1F300, 0x1F5FF),
  Tuple3(UnicodeBlock.unicodeEmoticons, 0x1F600, 0x1F64F),
  Tuple3(UnicodeBlock.unicodeTransportAndMapSymbols, 0x1F680, 0x1F6FF),
  Tuple3(UnicodeBlock.unicodeAlchemicalSymbols, 0x1F700, 0x1F77F),
  Tuple3(UnicodeBlock.unicodeCjkUnifiedIdeographsExtensionB, 0x20000, 0x2A6DF),
  Tuple3(UnicodeBlock.unicodeCjkUnifiedIdeographsExtensionC, 0x2A700, 0x2B73F),
  Tuple3(UnicodeBlock.unicodeCjkUnifiedIdeographsExtensionD, 0x2B740, 0x2B81F),
  Tuple3(UnicodeBlock.unicodeCjkCompatibilityIdeographsSupplement, 0x2F800,
      0x2FA1F),
  Tuple3(UnicodeBlock.unicodeTags, 0xE0000, 0xE007F),
  Tuple3(UnicodeBlock.unicodeVariationSelectorsSupplement, 0xE0100, 0xE01EF),
  Tuple3(UnicodeBlock.unicodeSupplementaryPrivateUseAreaA, 0xF0000, 0xFFFFF),
  Tuple3(UnicodeBlock.unicodeSupplementaryPrivateUseAreaB, 0x100000, 0x10FFFF),
];

final int numBlocks = _unicodeBlocks.length;

UnicodeBlock? unicodeBlock(String ch) {
  int cp = ch.codeUnitAt(0);

  if (cp <= 0x7F) {
    return UnicodeBlock.unicodeBasicLatin;
  }

  int be = 0;
  int en = numBlocks - 1;

  while (be <= en) {
    int mid = (be + en) >> 1;
    Tuple3<UnicodeBlock, int, int> block = _unicodeBlocks[mid];
    UnicodeBlock name = block.item1;
    int start = block.item2;
    int end = block.item3;

    if (start <= cp && cp <= end) {
      return name;
    }
    if (cp < start) {
      en = mid - 1;
    } else {
      be = mid + 1;
    }
  }
  return null;
}
