// This is generated by generate_language_profiles.py
import 'profiles_data/lang_af.dart';
import 'profiles_data/lang_ar.dart';
import 'profiles_data/lang_bg.dart';
import 'profiles_data/lang_bn.dart';
import 'profiles_data/lang_ca.dart';
import 'profiles_data/lang_cs.dart';
import 'profiles_data/lang_cy.dart';
import 'profiles_data/lang_da.dart';
import 'profiles_data/lang_de.dart';
import 'profiles_data/lang_el.dart';
import 'profiles_data/lang_en.dart';
import 'profiles_data/lang_es.dart';
import 'profiles_data/lang_et.dart';
import 'profiles_data/lang_fa.dart';
import 'profiles_data/lang_fi.dart';
import 'profiles_data/lang_fr.dart';
import 'profiles_data/lang_gu.dart';
import 'profiles_data/lang_he.dart';
import 'profiles_data/lang_hi.dart';
import 'profiles_data/lang_hr.dart';
import 'profiles_data/lang_hu.dart';
import 'profiles_data/lang_id.dart';
import 'profiles_data/lang_it.dart';
import 'profiles_data/lang_ja.dart';
import 'profiles_data/lang_kn.dart';
import 'profiles_data/lang_ko.dart';
import 'profiles_data/lang_lt.dart';
import 'profiles_data/lang_lv.dart';
import 'profiles_data/lang_mk.dart';
import 'profiles_data/lang_ml.dart';
import 'profiles_data/lang_mr.dart';
import 'profiles_data/lang_ne.dart';
import 'profiles_data/lang_nl.dart';
import 'profiles_data/lang_no.dart';
import 'profiles_data/lang_pa.dart';
import 'profiles_data/lang_pl.dart';
import 'profiles_data/lang_pt.dart';
import 'profiles_data/lang_ro.dart';
import 'profiles_data/lang_ru.dart';
import 'profiles_data/lang_sk.dart';
import 'profiles_data/lang_sl.dart';
import 'profiles_data/lang_so.dart';
import 'profiles_data/lang_sq.dart';
import 'profiles_data/lang_sv.dart';
import 'profiles_data/lang_sw.dart';
import 'profiles_data/lang_ta.dart';
import 'profiles_data/lang_te.dart';
import 'profiles_data/lang_th.dart';
import 'profiles_data/lang_tl.dart';
import 'profiles_data/lang_tr.dart';
import 'profiles_data/lang_uk.dart';
import 'profiles_data/lang_ur.dart';
import 'profiles_data/lang_vi.dart';
import 'profiles_data/lang_zhcn.dart';
import 'profiles_data/lang_zhtw.dart';

const allLanguageProfiles = [
  afLanguageData,
  arLanguageData,
  bgLanguageData,
  bnLanguageData,
  caLanguageData,
  csLanguageData,
  cyLanguageData,
  daLanguageData,
  deLanguageData,
  elLanguageData,
  enLanguageData,
  esLanguageData,
  etLanguageData,
  faLanguageData,
  fiLanguageData,
  frLanguageData,
  guLanguageData,
  heLanguageData,
  hiLanguageData,
  hrLanguageData,
  huLanguageData,
  idLanguageData,
  itLanguageData,
  jaLanguageData,
  knLanguageData,
  koLanguageData,
  ltLanguageData,
  lvLanguageData,
  mkLanguageData,
  mlLanguageData,
  mrLanguageData,
  neLanguageData,
  nlLanguageData,
  noLanguageData,
  paLanguageData,
  plLanguageData,
  ptLanguageData,
  roLanguageData,
  ruLanguageData,
  skLanguageData,
  slLanguageData,
  soLanguageData,
  sqLanguageData,
  svLanguageData,
  swLanguageData,
  taLanguageData,
  teLanguageData,
  thLanguageData,
  tlLanguageData,
  trLanguageData,
  ukLanguageData,
  urLanguageData,
  viLanguageData,
  zhcnLanguageData,
  zhtwLanguageData,
];
